sudo: required
dist: xenial

language: node_js
node_js: 12

install:
  - yarn

script:
  - yarn travix neko
  - yarn travix node
  - yarn travix python
  # - yarn travix java
  - yarn travix php
  - yarn travix cpp
  # - yarn travix cs
  # - yarn travix lua
